
data = {'created_at': 'Tue Jan 19 16:50:38 +0000 2021',
        'id': 1,
        'id_str': '1351572786733408258',
        'text': 'text',
        'source': '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
        'truncated': False,
        'in_reply_to_status_id': None,
        'in_reply_to_status_id_str': None,
        'in_reply_to_user_id': None,
        'in_reply_to_user_id_str': None,
        'in_reply_to_screen_name': None,
        'user': {'id': 1,
                 'id_str': '1258085635082063882',
                 'name': 'name',
                 'screen_name': 'screen_name',
                 'location': None,
                 'url': None,
                 'description': "Don't ever doubt yourself or waste a second of your life. It's too short and you're too special.{ A.G}\n\n(fan account) 𝑆h𝑒/𝐻𝑒𝑟",
                 'translator_type': 'none', 'protected': False,
                 'verified': False,
                 'followers_count': 1393,
                 'friends_count': 2660,
                 'listed_count': 3,
                 'favourites_count': 34450,
                 'statuses_count': 10834,
                 'created_at': 'Wed May 06 17:26:17 +0000 2020',
                 'utc_offset': None,
                 'time_zone': None,
                 'geo_enabled': False,
                 'lang': None,
                 'contributors_enabled': False,
                 'is_translator': False,
                 'profile_background_color': 'F5F8FA',
                 'profile_background_image_url': '',
                 'profile_background_image_url_https': '',
                 'profile_background_tile': False,
                 'profile_link_color': '1DA1F2',
                 'profile_sidebar_border_color': 'C0DEED',
                 'profile_sidebar_fill_color': 'DDEEF6',
                 'profile_text_color': '333333',
                 'profile_use_background_image': True,
                 'profile_image_url': 'http://pbs.twimg.com/profile_images/1349888525915860992/mnNs1RlN_normal.jpg',
                 'profile_image_url_https': 'https://pbs.twimg.com/profile_images/1349888525915860992/mnNs1RlN_normal.jpg',
                 'profile_banner_url': 'https://pbs.twimg.com/profile_banners/1258085635082063882/1610672693',
                 'default_profile': True,
                 'default_profile_image': False,
                 'following': None,
                 'follow_request_sent': None,
                 'notifications': None},
        'geo': None,
        'coordinates': None,
        'place': None,
        'contributors': None,
        'retweeted_status': {'created_at': 'Tue Jan 19 12:44:40 +0000 2021',
                             'id': 1351510888667357186,
                             'id_str': '1351510888667357186',
                             'text': 'Justin Bieber with his beliebers; a long and beautiful thread \n#BeliebersDay #BelieberDay',
                             'source': '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
                             'truncated': False,
                             'in_reply_to_status_id': None,
                             'in_reply_to_status_id_str': None,
                             'in_reply_to_user_id': None,
                             'in_reply_to_user_id_str': None,
                             'in_reply_to_screen_name': None,
                             'user': {'id': 1245331093047447552,
                                      'id_str': '1245331093047447552',
                                      'name': 'irene🧸🥊|| ANYONE',
                                      'screen_name': 'buzztinxpurpose',
                                      'location': 'madrid',
                                      'url': None,
                                      'description': '#𝐉𝐔𝐒𝐓𝐈𝐍: who you are is enough✨• • she/her • • jb x ag',
                                      'translator_type': 'none',
                                      'protected': False,
                                      'verified': False,
                                      'followers_count': 1888,
                                      'friends_count': 1868,
                                      'listed_count': 11,
                                      'favourites_count': 20393,
                                      'statuses_count': 17593,
                                      'created_at': 'Wed Apr 01 12:44:14 +0000 2020',
                                      'utc_offset': None,
                                      'time_zone': None,
                                      'geo_enabled': True,
                                      'lang': None,
                                      'contributors_enabled': False,
                                      'is_translator': False,
                                      'profile_background_color': 'F5F8FA',
                                      'profile_background_image_url': '',
                                      'profile_background_image_url_https': '',
                                      'profile_background_tile': False,
                                      'profile_link_color': '1DA1F2',
                                      'profile_sidebar_border_color': 'C0DEED',
                                      'profile_sidebar_fill_color': 'DDEEF6',
                                      'profile_text_color': '333333',
                                      'profile_use_background_image': True,
                                      'profile_image_url': 'http://pbs.twimg.com/profile_images/1345497857617502210/Djuq18Cm_normal.jpg',
                                      'profile_image_url_https': 'https://pbs.twimg.com/profile_images/1345497857617502210/Djuq18Cm_normal.jpg',
                                      'profile_banner_url': 'https://pbs.twimg.com/profile_banners/1245331093047447552/1610565121',
                                      'default_profile': True,
                                      'default_profile_image': False,
                                      'following': None,
                                      'follow_request_sent': None,
                                      'notifications': None},
                             'geo': None,
                             'coordinates': None,
                             'place': None,
                             'contributors': None,
                             'is_quote_status': False,
                             'quote_count': 6,
                             'reply_count': 2,
                             'retweet_count': 10,
                             'favorite_count': 41,
                             'entities': {'hashtags': [{'text': 'BeliebersDay',
                                                        'indices': [63, 76]},
                                                       {'text': 'BelieberDay', 'indices': [77, 89]}],
                                          'urls': [],
                                          'user_mentions': [],
                                          'symbols': []},
                             'favorited': False,
                             'retweeted': False,
                             'filter_level': 'low',
                             'lang': 'en'},
        'is_quote_status': False,
        'quote_count': 0,
        'reply_count': 0,
        'retweet_count': 0,
        'favorite_count': 0,
        'entities': {'hashtags': [{'text': 'BeliebersDay', 'indices': [84, 97]},
                                  {'text': 'BelieberDay', 'indices': [98, 110]}],
                     'urls': [],
                     'user_mentions': [{'screen_name': 'buzztinxpurpose',
                                        'name': 'irene🧸🥊|| ANYONE',
                                        'id': 1245331093047447552,
                                        'id_str': '1245331093047447552',
                                        'indices': [3, 19]}],
                     'symbols': []},
        'favorited': False,
        'retweeted': False,
        'filter_level': 'low',
        'lang': 'en',
        'timestamp_ms': '1611075038022'}